import {
  Lightbulb,
  BookOpen,
  Users,
  Tent,
  HeartHandshake,
  Compass,
  Sparkles,
  Target,
  Search,
  PenTool,
  ClipboardCheck,
} from "lucide-react";

export const domains = [
  {
    icon: Lightbulb,
    title: "Design Thinking",
    description:
      "กระบวนการคิดเชิงออกแบบเพื่อแก้ปัญหาและสร้างนวัตกรรมที่ใช้ได้จริง โดยมีมนุษย์หรือผู้ใช้เป็นศูนย์กลาง ผ่านขั้นตอน Empathize, Define, Ideate, Prototype และ Test พร้อมฝึกทักษะการสัมภาษณ์ การฟัง และการนำเสนอ",
    formats: [
      { name: "Community Engagement", detail: "เน้น Empathize, Define และ Ideate ผ่านการลงพื้นที่ชุมชนจริง" },
      { name: "Hackathon", detail: "เน้น Ideate, Prototype และ Test เพื่อสร้างต้นแบบนวัตกรรม" },
    ],
  },
  {
    icon: BookOpen,
    title: "Storytelling",
    description:
      "การถ่ายทอดเรื่องราวและอารมณ์ความรู้สึกจากผู้พูดสู่ผู้ฟัง เพื่อสร้างการตระหนักรู้และการเปลี่ยนแปลง ผ่านรูปแบบที่หลากหลาย ทั้งการเล่าในที่สาธารณะ การแสดง หรือละคร ฝึกการสร้างโครงเรื่อง การพูดในที่สาธารณะ และการนำเสนออย่างสร้างสรรค์",
    formats: [
      { name: "Public Speaking", detail: "ฝึกการค้นหาเรื่องราว จัดเรียงโครงเรื่อง และการพูดต่อหน้าผู้ฟัง" },
      { name: "Creative Communication", detail: "ถ่ายทอดเรื่องราวผ่านละคร เสียง และการแสดงสร้างสรรค์" },
    ],
  },
  {
    icon: Users,
    title: "Leadership",
    description:
      "ทักษะการสร้างแรงบันดาลใจ กระตุ้นศักยภาพ และนำพาผู้อื่นไปสู่เป้าหมายร่วมกันอย่างมีประสิทธิภาพ ผ่านความเข้าใจตนเอง การสื่อสาร การตัดสินใจภายใต้ความกดดัน และการทำงานร่วมกับผู้อื่นอย่างสร้างสรรค์",
    formats: [
      { name: "Building Mindset", detail: "สร้างความเข้าใจในตนเองและนิยามความเป็นผู้นำที่หลากหลาย" },
      { name: "Skill Applied", detail: "ทดลองใช้ทักษะผู้นำผ่านสถานการณ์จำลองและ Game Simulation" },
    ],
  },
];

export const signatureCamp = {
  title: "Signature Camp",
  points: [
    "สามารถปรับแต่งเนื้อหาสำหรับโรงเรียนหรือองค์กรได้โดยเฉพาะ",
    "มีความหลากหลายในระยะเวลาจัดกิจกรรม ตั้งแต่ครึ่งวันจนถึงหลายวัน",
    "สร้างการเรียนรู้ทั้งด้าน Soft Skills และ Hard Skills ควบคู่กัน",
    "ประยุกต์ได้ทั้งค่ายทั่วไป หรือค่ายสำหรับโครงการพิเศษเฉพาะทาง",
  ],
};

export const formatTypes = [
  {
    icon: Tent,
    name: "Camp",
    description: "ประสบการณ์การเรียนรู้แบบหลายวันที่เน้นการสร้างทักษะผ่านกิจกรรมลงมือทำจริง",
  },
  {
    icon: ClipboardCheck,
    name: "Workshop",
    description: "กิจกรรมระยะสั้นที่เน้นการเรียนรู้เชิงปฏิบัติ การมีส่วนร่วม และผลลัพธ์ที่ชัดเจน",
  },
  {
    icon: Sparkles,
    name: "Miscellaneous",
    description: "รูปแบบการเรียนรู้อื่น ๆ เช่น การบรรยาย นิทรรศการการเรียนรู้ และงานอีเวนต์ต่าง ๆ",
  },
];

export const expertiseTags = [
  "Design Thinking",
  "Storytelling",
  "Leadership",
  "Interpersonal Communication",
  "Conflict Management",
  "Self-Awareness",
  "Creative Thinking",
  "Social Innovation",
  "Problem-Based Learning",
  "Creative Communication",
  "Effective Feedback",
  "Game for Learning",
  "Team Building",
];

export const process = [
  {
    icon: Search,
    step: "01",
    title: "ทำความเข้าใจและออกแบบร่วมกัน",
    description: "ทำความเข้าใจบริบทผู้เรียนและเป้าหมายของโรงเรียนหรือองค์กร เพื่อออกแบบหลักสูตรที่ตอบโจทย์เฉพาะ",
  },
  {
    icon: PenTool,
    step: "02",
    title: "ออกแบบกระบวนการเรียนรู้",
    description: "วางโครงสร้างกิจกรรม เนื้อหา และเครื่องมือการเรียนรู้ที่เหมาะสมตลอดทั้งหลักสูตร",
  },
  {
    icon: Users,
    step: "03",
    title: "จัดกระบวนการเรียนรู้",
    description: "ทีมวิทยากรลงพื้นที่จัดกระบวนการ ดูแล และให้คำปรึกษาแก่ผู้เรียนตลอดกิจกรรม",
  },
  {
    icon: ClipboardCheck,
    step: "04",
    title: "ถอดบทเรียนและติดตามผล",
    description: "สรุปผลลัพธ์การเรียนรู้ร่วมกับผู้เรียน และติดตามผลการนำไปใช้หลังจบโครงการ",
  },
];

export const values = [
  {
    icon: HeartHandshake,
    title: "ผู้เรียนเป็นศูนย์กลาง",
    description: "ออกแบบทุกกระบวนการโดยเข้าใจความต้องการที่แท้จริงของผู้เรียนเป็นอันดับแรก",
  },
  {
    icon: Compass,
    title: "เรียนรู้ผ่านประสบการณ์จริง",
    description: "ใช้กระบวนการ Facilitation เกมการเรียนรู้แบบ Interactive และกิจกรรมสร้างนวัตกรรม",
  },
  {
    icon: Sparkles,
    title: "พัฒนาอย่างรอบด้าน",
    description: "มุ่งเน้นการพัฒนาทักษะ ความคิด และจิตวิญญาณของผู้เรียนให้เติบโตไปพร้อมกัน",
  },
  {
    icon: Target,
    title: "ออกแบบเฉพาะทาง",
    description: "ปรับแต่งเนื้อหาและกระบวนการให้เหมาะกับบริบทของแต่ละโรงเรียนและองค์กรโดยเฉพาะ",
  },
];

export const team = [
  {
    name: "ณภัทร กิจสนาโยธิน",
    nickname: "ปาล์ม",
    image: "/team/palm.jpg",
    role: "Chief Executive Officer (CEO)",
    education: "Bachelor of Arts (Learning Sciences), First-Class Honours, Thammasat University",
  },
  {
    name: "จิรสิน จานะพร",
    nickname: "สิน",
    role: "Chief Financial Officer (CFO)",
    education: "Bachelor of Science in Statistics, Second-Class Honours, Chulalongkorn University",
  },
  {
    name: "ขวัญชนก สงฆ์มีสุข",
    nickname: "ของขวัญ",
    role: "General Manager (GM)",
    education: "Bachelor of Arts (Learning Sciences), First-Class Honours, Thammasat University",
  },
  {
    name: "ธนภัทร สงนวน",
    nickname: "กันตะ",
    role: "Learning Designer",
    education: "Bachelor of Arts (Learning Sciences), First-Class Honours, Thammasat University",
    expertise: [
      "Innovative Thinking and Design Thinking",
      "Experiential Learning and Reflection",
      "Civic Imagination",
      "Creative Drama",
      "Leadership skill and Team Building",
      "Conflict Management",
    ],
  },
  {
    name: "แทนไท ตั้งวนิชกุล",
    nickname: "แทนไท",
    role: "Learning Designer",
    education: "Bachelor of Arts (Learning Sciences), First-Class Honours, Thammasat University",
    expertise: [
      "Creative Communication",
      "Storytelling",
      "Tales-based Learning",
      "Creative Drama",
      "Drama/Theatre for Education",
      "Community Art and Culture Learning",
    ],
  },
];

export const stats = [
  { value: "45+", label: "โครงการที่จัดขึ้น" },
  { value: "5,000+", label: "ผู้เรียนที่เข้าร่วมกิจกรรม" },
  { value: "35+", label: "องค์กรและโรงเรียนพันธมิตร" },
  { value: "3+", label: "ปีของการดำเนินงาน" },
];

export const partners = [
  { name: "Suankularb Wittayalai School", logo: "/partners/suankularb.png" },
  { name: "Thammasat University (LSEd)", logo: "/partners/thammasat_lsed.png" },
  { name: "Assumption College", logo: "/partners/assumption.png" },
  { name: "Chulalongkorn Business Administration", logo: "/partners/cba.png" },
  { name: "Giftwise Asia", logo: "/partners/giftwise.png" },
  { name: "TK Park", logo: "/partners/tkpark.png" },
  { name: "World Wildlife Fund (WWF)", logo: "/partners/wwf.png" },
  { name: "Saint Gabriel's College", logo: "/partners/saint_gabriel.png" },
  { name: "Rights Beyond Border", logo: "/partners/rights_beyond_border.png" },
  { name: "Mitr Phol Group", logo: "/partners/mitr_phol.png" },
  { name: "Thammasat Secondary School", logo: "/partners/thammasat_secondary.png" },
  { name: "VetMed KU", logo: "/partners/vetmed_ku.png" },
  { name: "House of Wisdom TU", logo: "/partners/house_of_wisdom_tu.png" },
  { name: "Bangkok Christian College", logo: "/partners/bangkok_christian.png" },
  { name: "Satriwithaya School", logo: "/partners/satriwithaya.png" },
  { name: "Khemasiri Memorial School", logo: "/partners/khemasiri.png" },
  { name: "Triamudomsuksa Pattanakarn Nonthaburi School", logo: "/partners/triamudomsuksa.png" },
  { name: "Samut Prakan Provincial Administrative Organization", logo: "/partners/samut_prakan.png" },
  { name: "SMO Chulalongkorn Business School", logo: "/partners/smo_banshi.png" },
  { name: "กวศ.", logo: "/partners/kwas.png" },
  { name: "CaMP by ChAMP", logo: "/partners/camp_by_champ.png" },
];

const portfolioRaw = [
  // Camps
  {
    category: "camp",
    images: ["/work/01-1.jpg", "/work/01-2.jpg", "/work/01-3.jpg"],
    sortDate: "2024-06-10",
    levels: ["มัธยม"],
    title: "SK Design Thinking Experience Camp",
    date: "10-12 มิ.ย. 2567",
    duration: "3 วัน",
    participants: "170 คน",
    topics: ["Design Thinking process", "Innovation", "Community Engagement", "Public speaking"],
    partner: "Suankularb Wittayalai School",
  },
  {
    category: "camp",
    images: ["/work/02-1.jpg", "/work/02-2.jpg", "/work/02-3.jpg", "/work/02-4.jpg"],
    sortDate: "2024-06-24",
    levels: ["มัธยม"],
    title: "Camp พัฒนาทักษะผู้ประกอบการบนฐานชุมชน",
    date: "24-27 มิ.ย. 2567",
    duration: "4 วัน",
    participants: "60 คน",
    topics: ["Local Development", "Drama", "Confidence", "Presentation"],
    partner: "LSEd TU, โครงการโรงเรียนร่วมพัฒนา และ Ban Bangmak School",
  },
  {
    category: "camp",
    images: ["/work/03-1.jpg", "/work/03-2.jpg", "/work/03-3.jpg", "/work/03-4.jpg"],
    sortDate: "2024-10-01",
    levels: ["มัธยม"],
    title: "SK Gentleman Camp EP4: Experiencing Phra Nakhon",
    date: "1-3 ต.ค. 2567",
    duration: "3 วัน",
    participants: "100 คน",
    topics: ["Story-telling", "Community engagement", "Cultural heritages"],
    partner: "Greenmoons BKK, Satarana และ Suankularb Wittayalai School",
  },
  {
    category: "camp",
    images: ["/work/04-1.jpg", "/work/04-2.jpg", "/work/04-3.jpg"],
    sortDate: "2024-11-01",
    levels: ["มหาวิทยาลัย"],
    title: "LSEd Student Affairs Mid-Year Seminar 2024",
    date: "1-3 พ.ย. 2567",
    duration: "3 วัน",
    participants: "30 คน",
    topics: ["Project Management", "Risk Management", "Activity design", "Culture Management"],
    partner: "LSEd TU",
  },
  {
    category: "camp",
    images: ["/work/05-1.jpg", "/work/05-2.jpg", "/work/05-3.jpg", "/work/05-4.jpg"],
    sortDate: "2025-06-09",
    levels: ["มัธยม"],
    title: "SK Design Thinking Camp 2025",
    date: "9-11 มิ.ย. 2568",
    duration: "3 วัน",
    participants: "100 คน",
    topics: ["Design Thinking", "Social Problem Analysis", "Social Innovation", "Community engagement"],
    partner: "Suankularb Wittayalai School และ Bang Bua Thong City Municipality",
  },
  {
    category: "camp",
    images: ["/work/06-1.jpg", "/work/06-2.jpg", "/work/06-4.jpg", "/work/06-5.jpg"],
    sortDate: "2025-10-24",
    levels: ["มัธยม", "มหาวิทยาลัย"],
    title: "Rise Up: Young Leaders Driving Human Rights and Creative Change",
    date: "24-26 ต.ค. 2568",
    duration: "3 วัน",
    participants: "50 คน",
    topics: ["Problem Discovery", "Creative Communication", "Storytelling", "Theory of Change", "Advocacy Design"],
    partner: "Rights Beyond Border",
  },
  {
    category: "camp",
    images: ["/work/07-1.jpg", "/work/07-2.jpg", "/work/07-3.jpg", "/work/07-4.jpg"],
    sortDate: "2026-05-20",
    levels: ["มัธยม"],
    title: "ค่ายผู้นำรุ่นใหม่หัวใจพัฒนา รุ่นที่ 18 - Leadership Camp",
    date: "20-22 พ.ค. 2569",
    duration: "3 วัน",
    participants: "130 คน",
    topics: ["DISC for leadership", "Leadership skills/mindsets", "Working toolkits", "Team bonding"],
    partner: "Saint Gabriel's College",
  },
  {
    category: "camp",
    images: ["/work/08-1.jpg", "/work/08-2.jpg", "/work/08-3.jpg", "/work/08-4.jpg"],
    sortDate: "2026-06-22",
    levels: ["มัธยม"],
    title: "SK Design Thinking Camp 2026",
    date: "22-24 มิ.ย. 2569",
    duration: "3 วัน",
    participants: "150 คน",
    topics: ["Design Thinking", "Social Problem Analysis", "Social Innovation", "Community engagement"],
    partner: "Suankularb Wittayalai School และ Nakhonpathom City Municipality",
  },
  {
    category: "camp",
    images: ["/work/09-1.jpg", "/work/09-2.jpg", "/work/09-4.jpg", "/work/09-5.jpg"],
    sortDate: "2026-06-27",
    levels: ["มัธยม", "มหาวิทยาลัย"],
    title: "Rise Up: Transforming Leaders into Next-Gen Trainers",
    date: "27-29 มิ.ย. 2569",
    duration: "3 วัน",
    participants: "50 คน",
    topics: ["Advocacy Design", "Knowledge Management", "Learning Design", "Demo Class"],
    partner: "Rights Beyond Border",
  },
  // Workshops
  {
    category: "workshop",
    images: ["/work/10-1.jpg", "/work/10-2.jpg", "/work/10-3.jpg", "/work/10-4.jpg"],
    sortDate: "2023-02-01",
    levels: ["มัธยม", "มหาวิทยาลัย"],
    title: "Thai Youth's Civic Imagination and Social Innovation Project",
    date: "ก.พ. 2566 - ม.ค. 2567",
    duration: "11 เดือน",
    participants: "20 คน",
    topics: ["Civic imagination", "Social Innovation by Design Thinking", "Creative Communication"],
    partner: "LSEd TU และ the101.pub",
  },
  {
    category: "workshop",
    images: ["/work/11-1.jpg", "/work/11-2.jpg", "/work/11-3.jpg", "/work/11-4.jpg"],
    sortDate: "2024-02-01",
    levels: ["มัธยม"],
    title: "Workshop \"ห้องเรียนไร้กรอบขอบชีส\"",
    date: "ก.พ. - เม.ย. 2567",
    duration: "3 เดือน",
    participants: "120 คน",
    topics: ["Social Normalization", "Human rights", "Self-awareness", "Violence"],
    partner: "TK Park",
  },
  {
    category: "workshop",
    images: ["/work/12-1.jpg", "/work/12-2.jpg", "/work/12-3.jpg", "/work/12-4.jpg"],
    sortDate: "2024-03-05",
    levels: ["มัธยม"],
    title: "Problem-based Learning Camp",
    date: "5 มี.ค. 2567",
    duration: "4 ชั่วโมง",
    participants: "70 คน",
    topics: ["Problem-based Learning", "Problem Solving", "Science Literacy"],
    partner: "Satthasamut School",
  },
  {
    category: "workshop",
    images: ["/work/13-1.jpg", "/work/13-3.jpg"],
    sortDate: "2024-03-16",
    levels: ["องค์กร"],
    title: "CBA Middle Manager Workshop",
    date: "16 มี.ค. 2567",
    duration: "3 ชั่วโมง",
    participants: "60 คน",
    topics: ["Understand how business run", "Adaptability Quotient", "Team building"],
    partner: "Chulalongkorn Business Administration (CBA)",
  },
  {
    category: "workshop",
    images: ["/work/14-1.jpg", "/work/14-2.jpg", "/work/14-3.jpg"],
    sortDate: "2024-04-01",
    levels: ["มัธยม"],
    title: "Dream Expo, Wooden Bridge and Catapult Workshop",
    date: "1-3 เม.ย. 2567",
    duration: "3 วัน",
    participants: "300 คน",
    topics: ["Weight Distribution", "Structural Integrity", "Energy Transformation", "Projectile"],
    partner: "Assumption College",
  },
  {
    category: "workshop",
    images: ["/work/15-1.jpg", "/work/15-2.jpg", "/work/15-3.jpg"],
    sortDate: "2024-05-18",
    levels: ["ประถม", "มัธยม"],
    title: "Puppet Theatre Workshop",
    date: "18 พ.ค. 2567",
    duration: "4 ชั่วโมง",
    participants: "20 คน",
    topics: ["Puppet making", "Applied theatre", "Environmental-awareness"],
    partner: "Pathumyouth, Influencer th และ สสส.",
  },
  {
    category: "workshop",
    images: ["/work/16-1.jpg", "/work/16-2.jpg", "/work/16-3.jpg"],
    sortDate: "2024-05-25",
    levels: ["ครู"],
    title: "Environmental-awareness for Teacher",
    date: "25-26 พ.ค. 2567",
    duration: "2 วัน",
    participants: "300 คน",
    topics: ["Garbage recycling", "Environmental-awareness", "Creative Drama"],
    partner: "World Wildlife Fund, Ranong Recycle for Environment และ Surat Thani City Municipality",
  },
  {
    category: "workshop",
    images: ["/work/17-1.jpg", "/work/17-2.jpg", "/work/17-3.jpg"],
    sortDate: "2024-06-20",
    levels: ["มัธยม"],
    title: "Herbal Inhalant Making Workshop",
    date: "20 มิ.ย. 2567",
    duration: "4 ชั่วโมง",
    participants: "100 คน",
    topics: ["Thai culture", "Properties of herbs", "Inhalant making"],
    partner: "Amnuay Silpa School",
  },
  {
    category: "workshop",
    images: ["/work/18-1.jpg", "/work/18-2.jpg", "/work/18-3.jpg"],
    sortDate: "2024-07-12",
    levels: ["องค์กร"],
    title: "Giftwise's Q2 Townhall 2024",
    date: "12 ก.ค. 2567",
    duration: "3 ชั่วโมง",
    participants: "70 คน",
    topics: ["Active Listening", "Effective Feedback", "Non-violence Communication"],
    partner: "Giftwise Asia",
  },
  {
    category: "workshop",
    images: ["/work/19-1.jpg", "/work/19-2.jpg", "/work/19-3.jpg", "/work/19-4.jpg"],
    sortDate: "2024-08-04",
    levels: ["มัธยม"],
    title: "Workshop \"คนตัวเล็ก ขอเล่นใหญ่\" @Learning Fest 2024",
    date: "4 ส.ค. 2567",
    duration: "1 วัน",
    participants: "25 คน",
    topics: ["Civic Imagination", "Social Problem Analysis", "Self-Awareness", "Social Innovation"],
    partner: "TK Park",
  },
  {
    category: "workshop",
    images: ["/work/20-1.jpg", "/work/20-2.jpg", "/work/20-3.jpg", "/work/20-4.jpg"],
    sortDate: "2024-09-13",
    levels: ["ประถม"],
    title: "Workshop \"การทำสื่อสร้างสรรค์และละครเพื่อการเรียนรู้\"",
    date: "13 ก.ย. 2567",
    duration: "1 วัน",
    participants: "110 คน",
    topics: ["Creative Drama", "Team building"],
    partner: "วิทยากรทีมงานบ้านอรชุน และ โรงเรียนเทศบาลวัดป่าแพ่ง",
  },
  {
    category: "workshop",
    images: ["/work/21-1.jpg", "/work/21-2.jpg", "/work/21-3.jpg", "/work/21-4.jpg"],
    sortDate: "2024-11-27",
    levels: ["มัธยม"],
    title: "AC Engineer Camp 2024",
    date: "27 พ.ย. 2567",
    duration: "1 วัน",
    participants: "100 คน",
    topics: ["Basic Engineering", "STEM Education", "Projectile", "Product Design"],
    partner: "Assumption College",
  },
  {
    category: "workshop",
    images: ["/work/22-1.jpg", "/work/22-2.jpg", "/work/22-3.jpg"],
    sortDate: "2025-01-17",
    levels: ["องค์กร"],
    title: "Giftwise's Q1 Townhall 2025",
    date: "17 ม.ค. 2568",
    duration: "1 วัน",
    participants: "90 คน",
    topics: ["DISC for collaboration", "Team building", "Problem solving"],
    partner: "Giftwise Asia",
  },
  {
    category: "workshop",
    images: ["/work/23-1.jpg", "/work/23-2.jpg", "/work/23-3.jpg", "/work/23-4.jpg"],
    sortDate: "2025-02-01",
    levels: ["มหาวิทยาลัย"],
    title: "House of Wisdom TU Workshop 2025",
    date: "ก.พ. - เม.ย. 2568",
    duration: "3 เดือน / 8 sessions",
    participants: "300+ คน",
    topics: ["Performance arts", "Crafting", "Art", "Reflection"],
    partner: "House of Wisdom TU",
  },
  {
    category: "workshop",
    images: ["/work/24-1.jpg", "/work/24-2.jpg", "/work/24-3.jpg", "/work/24-4.jpg", "/work/24-5.jpg"],
    sortDate: "2025-03-27",
    levels: ["มัธยม"],
    title: "AC Engineering Design Process Workshop",
    date: "27 มี.ค. 2568",
    duration: "1 วัน",
    participants: "60 คน",
    topics: ["Basic Engineering", "STEM Education", "Design Process", "Truss Structure"],
    partner: "Assumption College",
  },
  {
    category: "workshop",
    images: ["/work/25-1.jpg", "/work/25-2.jpg", "/work/25-3.jpg", "/work/25-4.jpg"],
    sortDate: "2025-04-01",
    levels: ["มหาวิทยาลัย"],
    title: "VetMed KU Student Committee Orientation",
    date: "1 เม.ย. 2568",
    duration: "1 วัน",
    participants: "75 คน",
    topics: ["Non-violent communication", "Constructive Feedback", "Empathetic listening"],
    partner: "VetMed KU",
  },
  {
    category: "workshop",
    images: ["/work/26-1.jpg", "/work/26-2.jpg", "/work/26-4.jpg", "/work/26-5.jpg"],
    sortDate: "2025-05-02",
    levels: ["มัธยม"],
    title: "TSS Student Orientation Camp",
    date: "2-3 พ.ค. 2568",
    duration: "2 วัน",
    participants: "100 คน",
    topics: ["Team building", "Creativity", "Self-Awareness"],
    partner: "Thammasat Secondary School",
  },
  {
    category: "workshop",
    images: ["/work/27-1.jpg", "/work/27-2.jpg", "/work/27-4.jpg", "/work/27-5.jpg"],
    sortDate: "2025-05-20",
    levels: ["มัธยม"],
    title: "TSS Student Council Orientation",
    date: "20 พ.ค. 2568",
    duration: "1 วัน",
    participants: "25 คน",
    topics: ["DISC for leadership", "Non-violent communication", "Team building"],
    partner: "Thammasat Secondary School",
  },
  {
    category: "workshop",
    images: ["/work/28-1.jpg", "/work/28-2.jpg", "/work/28-4.jpg", "/work/28-5.jpg"],
    sortDate: "2025-05-25",
    levels: ["องค์กร"],
    title: "CBA Middle Manager Training: The Art of Teamwork",
    date: "25 พ.ค. 2568",
    duration: "1 วัน",
    participants: "25 คน",
    topics: ["Effective Communication", "Iceberg model", "GROW model for problem solving"],
    partner: "Chulalongkorn Business Administration (CBA)",
  },
  {
    category: "workshop",
    images: ["/work/29-1.jpg", "/work/29-2.jpg", "/work/29-4.jpg", "/work/29-5.jpg"],
    sortDate: "2025-06-21",
    levels: ["มหาวิทยาลัย"],
    title: "Unlock Your Leadership - SMO Banshix กวศ.",
    date: "21 มิ.ย. 2568",
    duration: "1 วัน",
    participants: "25 คน",
    topics: ["DISC for leadership", "Leadership skills/mindsets", "Team management"],
    partner: "SMO Banshi, ESC CU และ CaMP by ChAMP",
  },
  {
    category: "workshop",
    images: ["/work/30-1.jpg", "/work/30-2.jpg", "/work/30-3.jpg", "/work/30-4.jpg"],
    sortDate: "2025-11-13",
    levels: ["มัธยม"],
    title: "AC Bridgemaster Workshop",
    date: "13 พ.ย. 2568",
    duration: "1 วัน",
    participants: "100 คน",
    topics: ["Basic Engineering", "STEM Education", "Truss Structure"],
    partner: "Assumption College",
  },
  {
    category: "workshop",
    images: ["/work/31-1.jpg", "/work/31-2.jpg", "/work/31-3.jpg", "/work/31-4.jpg"],
    sortDate: "2025-12-20",
    levels: ["มัธยม"],
    title: "BCC Problem Discovery Class",
    date: "20 ธ.ค. 2568",
    duration: "1 วัน",
    participants: "40 คน",
    topics: ["Problem discovery", "Problem in daily life", "Solution Ideation"],
    partner: "Bangkok Christian College",
  },
  {
    category: "workshop",
    images: ["/work/32-1.jpg", "/work/32-2.jpg", "/work/32-3.jpg", "/work/32-4.jpg"],
    sortDate: "2026-02-20",
    levels: ["มัธยม"],
    title: "Awaken Your Purpose: วิชาปั้นฝัน 101",
    date: "20 ก.พ. 2569",
    duration: "1 วัน",
    participants: "50 คน",
    topics: ["Designing Your Life", "SMART Goals", "Finding Strength"],
    partner: "Bangkok Christian College",
  },
  {
    category: "workshop",
    images: ["/work/33-1.jpg", "/work/33-2.jpg", "/work/33-3.jpg", "/work/33-4.jpg"],
    sortDate: "2026-03-07",
    levels: ["มัธยม"],
    title: "AC STEM Workshop: Turbo Motion Challenge",
    date: "7 มี.ค. 2569",
    duration: "1 วัน",
    participants: "300 คน",
    topics: ["Basic Engineering", "STEM Education", "Basic Electrical Circuit", "Product Design"],
    partner: "Assumption College",
  },
  {
    category: "workshop",
    images: ["/work/34-1.jpg", "/work/34-2.jpg", "/work/34-3.jpg", "/work/34-4.jpg"],
    sortDate: "2026-03-31",
    levels: ["มัธยม"],
    title: "AC Escape Room - DREAM Expo 2026: Your Dream is…",
    date: "31 มี.ค. - 3 เม.ย. 2569",
    duration: "4 วัน / 16 sessions",
    participants: "400 คน",
    topics: ["Sciences in Daily Life", "Problem Solving", "Interdisciplinary Task"],
    partner: "Assumption College",
  },
  {
    category: "workshop",
    images: ["/work/35-1.jpg", "/work/35-2.jpg", "/work/35-3.jpg"],
    sortDate: "2026-03-31",
    levels: ["มัธยม"],
    title: "AC STEM Workshop: Wooden Skyscraper",
    date: "31 มี.ค. 2569",
    duration: "1 วัน",
    participants: "100 คน",
    topics: ["Basic Engineering", "STEM Education", "Truss Structure"],
    partner: "Assumption College",
  },
  {
    category: "workshop",
    images: ["/work/36-1.jpg", "/work/36-2.jpg", "/work/36-3.jpg", "/work/36-4.jpg"],
    sortDate: "2026-05-13",
    levels: ["ครู"],
    title: "House of The Saint: Teacher Orientation",
    date: "13 พ.ค. 2569",
    duration: "1 วัน",
    participants: "340 คน",
    topics: ["Student Care System", "Team bonding", "Project creation"],
    partner: "Saint Gabriel's College",
  },
  {
    category: "workshop",
    images: ["/work/37-1.jpg", "/work/37-2.jpg", "/work/37-3.jpg", "/work/37-4.jpg"],
    sortDate: "2026-06-19",
    levels: ["มัธยม"],
    title: "TPN English Magic Camp",
    date: "19 มิ.ย. 2569",
    duration: "1 วัน",
    participants: "100 คน",
    topics: ["English communication", "Debating in English", "Self-Confidence"],
    partner: "Triamudomsuksa Pattanakarn Nonthaburi School",
  },
  {
    category: "workshop",
    images: ["/work/38-1.jpg", "/work/38-2.jpg", "/work/38-4.jpg", "/work/38-5.jpg"],
    sortDate: "2026-07-09",
    levels: ["มัธยม"],
    title: "The Numbers Behind the Story",
    date: "9 ก.ค. 2569",
    duration: "1 วัน",
    participants: "26 คน",
    topics: ["Storytelling", "Body Language", "Talk Creation"],
    partner: "Satriwithaya School",
  },
  // Miscellaneous
  {
    category: "misc",
    images: ["/work/39-1.jpg", "/work/39-2.jpg", "/work/39-3.jpg"],
    sortDate: "2024-06-05",
    levels: ["ประถม", "มัธยม"],
    title: "Anti-addictive Substances Stageplay",
    date: "5 มิ.ย. - 19 ก.ค. 2567",
    duration: "24 วัน / 48 sessions",
    participants: "10,000+ คน",
    topics: ["Types of addictive substances", "Consequences of addiction", "Drama"],
    partner: "Samut Prakan Provincial Administrative Organization",
  },
  {
    category: "misc",
    images: ["/work/40-1.jpg", "/work/40-2.jpg", "/work/40-3.jpg", "/work/40-4.jpg"],
    sortDate: "2024-10-09",
    levels: ["มัธยม"],
    title: "เวที \"ร่วมพัฒนาโรงเรียน\" ณ โรงเรียนบ้านบางหมาก",
    date: "9-10 ต.ค. 2567",
    duration: "2 วัน",
    participants: "60 คน",
    topics: ["Creative Communication", "Applied theatre", "Cultural heritages"],
    partner: "LSEd TU, โครงการโรงเรียนร่วมพัฒนา และ Ban Bangmak School",
  },
  {
    category: "misc",
    images: ["/work/41-1.jpg", "/work/41-2.jpg", "/work/41-3.jpg", "/work/41-4.jpg"],
    sortDate: "2024-10-31",
    levels: ["มัธยม"],
    title: "SKE2024 Suankularb Innovation Contest",
    date: "31 ต.ค. 2567",
    duration: "1 วัน",
    participants: "80 คน",
    topics: ["Design Thinking", "Innovation", "Pitching"],
    partner: "Suankularb Wittayalai School",
  },
  {
    category: "misc",
    images: ["/work/42-1.jpg", "/work/42-2.jpg", "/work/42-3.jpg", "/work/42-4.jpg"],
    sortDate: "2024-11-09",
    levels: ["มัธยม", "มหาวิทยาลัย"],
    title: "SYSI Curate Your Pitch & Talk Workshop",
    date: "9 พ.ย. 2567",
    duration: "1 วัน",
    participants: "40 คน",
    topics: ["Story-telling for social innovation", "Pitching", "Stage Performance"],
    partner: "SYSI และ Connect Fest 3",
  },
  {
    category: "misc",
    images: ["/work/43-1.jpg", "/work/43-2.jpg", "/work/43-3.jpg"],
    sortDate: "2024-12-01",
    levels: ["ประถม"],
    title: "Interactive Learning Exhibition \"สายลับนากน้อย\"",
    date: "1 ธ.ค. 2567",
    duration: "1 วัน",
    participants: "200 คน",
    topics: ["Community engagement", "Cultural heritages", "Applied theatre"],
    partner: "LSEd TU และ โครงการโรงเรียนร่วมพัฒนา",
  },
  {
    category: "misc",
    images: ["/work/44-1.jpg", "/work/44-2.jpg"],
    sortDate: "2025-02-28",
    levels: ["องค์กร"],
    title: "Giftwise's Excel Training",
    date: "28 ก.พ. 2568",
    duration: "1 วัน",
    participants: "30 คน",
    topics: ["Excel for corporate"],
    partner: "Giftwise Asia",
  },
  {
    category: "misc",
    images: ["/work/45-1.jpg", "/work/45-2.jpg", "/work/45-3.jpg", "/work/45-4.jpg"],
    sortDate: "2025-07-07",
    levels: ["มัธยม"],
    title: "เส้นทางฝันกับพอร์ตในมือ - TCAS Portfolio Guidance",
    date: "7 ก.ค. 2568",
    duration: "1 วัน",
    participants: "300 คน",
    topics: ["Portfolio guidance", "Storytelling for Portfolio", "TCAS preparation"],
    partner: "Khemasiri Memorial School",
  },
  {
    category: "misc",
    images: ["/work/46-1.jpg", "/work/46-2.jpg", "/work/46-3.jpg", "/work/46-4.jpg", "/work/46-5.jpg"],
    sortDate: "2025-07-29",
    levels: ["มหาวิทยาลัย"],
    title: "YES Talent Camp 2025 - GenAI Hackathon - Orientation Day",
    date: "29 ก.ค. 2568",
    duration: "1 วัน",
    participants: "120 คน",
    topics: ["Teambuilding", "Potential Seeking", "Pitching Simulation"],
    partner: "Mitr Phol Group",
  },
  {
    category: "misc",
    images: ["/work/47-1.jpg", "/work/47-2.jpg", "/work/47-3.jpg", "/work/47-4.jpg"],
    sortDate: "2026-03-12",
    levels: ["มหาวิทยาลัย"],
    title: "ถอดบทเรียนสะท้อนคิด โครงการ \"Craft AI\"",
    date: "12 มี.ค. 2569",
    duration: "1 วัน",
    participants: "30 คน",
    topics: ["Reflection", "Learning Milestones", "Finding Next-step"],
    partner: "LSEd TU และ บพท.",
  },
];

export const portfolio = [...portfolioRaw].sort((a, b) =>
  b.sortDate.localeCompare(a.sortDate)
);
