import {
  Lightbulb,
  BookOpen,
  Users,
  Tent,
  HeartHandshake,
  Compass,
  Sparkles,
  Target,
  Search,
  PenTool,
  ClipboardCheck,
} from "lucide-react";

export const domains = [
  {
    icon: Lightbulb,
    title: "Design Thinking",
    description:
      "กระบวนการคิดเชิงออกแบบเพื่อแก้ปัญหาและสร้างนวัตกรรมที่ใช้ได้จริง โดยมีมนุษย์หรือผู้ใช้เป็นศูนย์กลาง ผ่านขั้นตอน Empathize, Define, Ideate, Prototype และ Test พร้อมฝึกทักษะการสัมภาษณ์ การฟัง และการนำเสนอ",
    formats: [
      { name: "Community Engagement", detail: "เน้น Empathize, Define และ Ideate ผ่านการลงพื้นที่ชุมชนจริง" },
      { name: "Hackathon", detail: "เน้น Ideate, Prototype และ Test เพื่อสร้างต้นแบบนวัตกรรม" },
    ],
  },
  {
    icon: BookOpen,
    title: "Storytelling",
    description:
      "การถ่ายทอดเรื่องราวและอารมณ์ความรู้สึกจากผู้พูดสู่ผู้ฟัง เพื่อสร้างการตระหนักรู้และการเปลี่ยนแปลง ผ่านรูปแบบที่หลากหลาย ทั้งการเล่าในที่สาธารณะ การแสดง หรือละคร ฝึกการสร้างโครงเรื่อง การพูดในที่สาธารณะ และการนำเสนออย่างสร้างสรรค์",
    formats: [
      { name: "Public Speaking", detail: "ฝึกการค้นหาเรื่องราว จัดเรียงโครงเรื่อง และการพูดต่อหน้าผู้ฟัง" },
      { name: "Creative Communication", detail: "ถ่ายทอดเรื่องราวผ่านละคร เสียง และการแสดงสร้างสรรค์" },
    ],
  },
  {
    icon: Users,
    title: "Leadership",
    description:
      "ทักษะการสร้างแรงบันดาลใจ กระตุ้นศักยภาพ และนำพาผู้อื่นไปสู่เป้าหมายร่วมกันอย่างมีประสิทธิภาพ ผ่านความเข้าใจตนเอง การสื่อสาร การตัดสินใจภายใต้ความกดดัน และการทำงานร่วมกับผู้อื่นอย่างสร้างสรรค์",
    formats: [
      { name: "Building Mindset", detail: "สร้างความเข้าใจในตนเองและนิยามความเป็นผู้นำที่หลากหลาย" },
      { name: "Skill Applied", detail: "ทดลองใช้ทักษะผู้นำผ่านสถานการณ์จำลองและ Game Simulation" },
    ],
  },
];

export const signatureCamp = {
  title: "Signature Camp",
  points: [
    "สามารถปรับแต่งเนื้อหาสำหรับโรงเรียนหรือองค์กรได้โดยเฉพาะ",
    "มีความหลากหลายในระยะเวลาจัดกิจกรรม ตั้งแต่ครึ่งวันจนถึงหลายวัน",
    "สร้างการเรียนรู้ทั้งด้าน Soft Skills และ Hard Skills ควบคู่กัน",
    "ประยุกต์ได้ทั้งค่ายทั่วไป หรือค่ายสำหรับโครงการพิเศษเฉพาะทาง",
  ],
};

export const formatTypes = [
  {
    icon: Tent,
    name: "Camp",
    description: "ประสบการณ์การเรียนรู้แบบหลายวันที่เน้นการสร้างทักษะผ่านกิจกรรมลงมือทำจริง",
  },
  {
    icon: ClipboardCheck,
    name: "Workshop",
    description: "กิจกรรมระยะสั้นที่เน้นการเรียนรู้เชิงปฏิบัติ การมีส่วนร่วม และผลลัพธ์ที่ชัดเจน",
  },
  {
    icon: Sparkles,
    name: "Miscellaneous",
    description: "รูปแบบการเรียนรู้อื่น ๆ เช่น การบรรยาย นิทรรศการการเรียนรู้ และงานอีเวนต์ต่าง ๆ",
  },
];

export const expertiseTags = [
  "Design Thinking",
  "Storytelling",
  "Leadership",
  "Interpersonal Communication",
  "Conflict Management",
  "Self-Awareness",
  "Creative Thinking",
  "Social Innovation",
  "Problem-Based Learning",
  "Creative Communication",
  "Effective Feedback",
  "Game for Learning",
  "Team Building",
];

export const process = [
  {
    icon: Search,
    step: "01",
    title: "ทำความเข้าใจและออกแบบร่วมกัน",
    description: "ทำความเข้าใจบริบทผู้เรียนและเป้าหมายของโรงเรียนหรือองค์กร เพื่อออกแบบหลักสูตรที่ตอบโจทย์เฉพาะ",
  },
  {
    icon: PenTool,
    step: "02",
    title: "ออกแบบกระบวนการเรียนรู้",
    description: "วางโครงสร้างกิจกรรม เนื้อหา และเครื่องมือการเรียนรู้ที่เหมาะสมตลอดทั้งหลักสูตร",
  },
  {
    icon: Users,
    step: "03",
    title: "จัดกระบวนการเรียนรู้",
    description: "ทีมวิทยากรลงพื้นที่จัดกระบวนการ ดูแล และให้คำปรึกษาแก่ผู้เรียนตลอดกิจกรรม",
  },
  {
    icon: ClipboardCheck,
    step: "04",
    title: "ถอดบทเรียนและติดตามผล",
    description: "สรุปผลลัพธ์การเรียนรู้ร่วมกับผู้เรียน และติดตามผลการนำไปใช้หลังจบโครงการ",
  },
];

export const values = [
  {
    icon: HeartHandshake,
    title: "ผู้เรียนเป็นศูนย์กลาง",
    description: "ออกแบบทุกกระบวนการโดยเข้าใจความต้องการที่แท้จริงของผู้เรียนเป็นอันดับแรก",
  },
  {
    icon: Compass,
    title: "เรียนรู้ผ่านประสบการณ์จริง",
    description: "ใช้กระบวนการ Facilitation เกมการเรียนรู้แบบ Interactive และกิจกรรมสร้างนวัตกรรม",
  },
  {
    icon: Sparkles,
    title: "พัฒนาอย่างรอบด้าน",
    description: "มุ่งเน้นการพัฒนาทักษะ ความคิด และจิตวิญญาณของผู้เรียนให้เติบโตไปพร้อมกัน",
  },
  {
    icon: Target,
    title: "ออกแบบเฉพาะทาง",
    description: "ปรับแต่งเนื้อหาและกระบวนการให้เหมาะกับบริบทของแต่ละโรงเรียนและองค์กรโดยเฉพาะ",
  },
];

export const team = [
  {
    name: "ณภัทร กิจสนาโยธิน",
    nickname: "ปาล์ม",
    role: "Chief Executive Officer (CEO)",
    education: "Bachelor of Arts (Learning Sciences), First-Class Honours, Thammasat University",
  },
  {
    name: "จิรสิน จานะพร",
    nickname: "สิน",
    role: "Chief Financial Officer (CFO)",
    education: "Bachelor of Science in Statistics, Second-Class Honours, Chulalongkorn University",
  },
  {
    name: "ขวัญชนก สงฆ์มีสุข",
    nickname: "ของขวัญ",
    role: "General Manager (GM)",
    education: "Bachelor of Arts (Learning Sciences), First-Class Honours, Thammasat University",
  },
  {
    name: "ธนภัทร สงนวน",
    nickname: "กันตะ",
    role: "Learning Designer",
    education: "Bachelor of Arts (Learning Sciences), Thammasat University",
    expertise: [
      "Innovative Thinking and Design Thinking",
      "Experiential Learning and Reflection",
      "Civic Imagination",
      "Creative Drama",
      "Leadership skill and Team Building",
      "Conflict Management",
    ],
  },
  {
    name: "แทนไท ตั้งวนิชกุล",
    nickname: "แทนไท",
    role: "Learning Designer",
    education: "Bachelor of Arts (Learning Sciences), Thammasat University",
    expertise: [
      "Creative Communication",
      "Storytelling",
      "Tales-based Learning",
      "Creative Drama",
      "Drama/Theatre for Education",
      "Community Art and Culture Learning",
    ],
  },
];

export const stats = [
  { value: "45+", label: "โครงการที่จัดขึ้น" },
  { value: "15,000+", label: "ผู้เรียนที่เข้าร่วมกิจกรรม" },
  { value: "35+", label: "องค์กรและโรงเรียนพันธมิตร" },
  { value: "3+", label: "ปีของการดำเนินงาน" },
];

export const partners = [
  "Suankularb Wittayalai School",
  "Thammasat University (LSEd)",
  "Assumption College",
  "Chulalongkorn Business Administration",
  "Giftwise Asia",
  "TK Park",
  "World Wildlife Fund (WWF)",
  "Saint Gabriel's College",
  "Rights Beyond Border",
  "Mitr Phol Group",
  "Thammasat Secondary School",
  "VetMed KU",
  "House of Wisdom TU",
  "Bangkok Christian College",
  "Satriwithaya School",
  "Khemasiri Memorial School",
  "Triamudomsuksa Pattanakarn Nonthaburi School",
  "Samut Prakan Provincial Administrative Organization",
];

const portfolioRaw = [
  // Camps
  {
    category: "camp",
    image: "/work/01.jpg",
    sortDate: "2024-06-10",
    title: "SK Design Thinking Experience Camp",
    date: "10-12 มิ.ย. 2567",
    duration: "3 วัน",
    participants: "170 คน",
    topics: ["Design Thinking process", "Innovation", "Community Engagement", "Public speaking"],
    partner: "Suankularb Wittayalai School",
  },
  {
    category: "camp",
    image: "/work/02.jpg",
    sortDate: "2024-06-24",
    title: "Camp พัฒนาทักษะผู้ประกอบการบนฐานชุมชน",
    date: "24-27 มิ.ย. 2567",
    duration: "4 วัน",
    participants: "60 คน",
    topics: ["Local Development", "Drama", "Confidence", "Presentation"],
    partner: "LSEd TU, โครงการโรงเรียนร่วมพัฒนา และ Ban Bangmak School",
  },
  {
    category: "camp",
    image: "/work/03.jpg",
    sortDate: "2024-10-01",
    title: "SK Gentleman Camp EP4: Experiencing Phra Nakhon",
    date: "1-3 ต.ค. 2567",
    duration: "3 วัน",
    participants: "100 คน",
    topics: ["Story-telling", "Community engagement", "Cultural heritages"],
    partner: "Greenmoons BKK, Satarana และ Suankularb Wittayalai School",
  },
  {
    category: "camp",
    image: "/work/04.jpg",
    sortDate: "2024-11-01",
    title: "LSEd Student Affairs Mid-Year Seminar 2024",
    date: "1-3 พ.ย. 2567",
    duration: "3 วัน",
    participants: "30 คน",
    topics: ["Project Management", "Risk Management", "Activity design", "Culture Management"],
    partner: "LSEd TU",
  },
  {
    category: "camp",
    image: "/work/05.jpg",
    sortDate: "2025-06-09",
    title: "SK Design Thinking Camp 2025",
    date: "9-11 มิ.ย. 2568",
    duration: "3 วัน",
    participants: "100 คน",
    topics: ["Design Thinking", "Social Problem Analysis", "Social Innovation", "Community engagement"],
    partner: "Suankularb Wittayalai School และ Bang Bua Thong City Municipality",
  },
  {
    category: "camp",
    image: "/work/06.jpg",
    sortDate: "2025-10-24",
    title: "Rise Up: Young Leaders Driving Human Rights and Creative Change",
    date: "24-26 ต.ค. 2568",
    duration: "3 วัน",
    participants: "50 คน",
    topics: ["Problem Discovery", "Creative Communication", "Storytelling", "Theory of Change", "Advocacy Design"],
    partner: "Rights Beyond Border",
  },
  {
    category: "camp",
    image: "/work/07.jpg",
    sortDate: "2026-05-20",
    title: "ค่ายผู้นำรุ่นใหม่หัวใจพัฒนา รุ่นที่ 18 - Leadership Camp",
    date: "20-22 พ.ค. 2569",
    duration: "3 วัน",
    participants: "130 คน",
    topics: ["DISC for leadership", "Leadership skills/mindsets", "Working toolkits", "Team bonding"],
    partner: "Saint Gabriel's College",
  },
  {
    category: "camp",
    image: "/work/08.jpg",
    sortDate: "2026-06-22",
    title: "SK Design Thinking Camp 2026",
    date: "22-24 มิ.ย. 2569",
    duration: "3 วัน",
    participants: "150 คน",
    topics: ["Design Thinking", "Social Problem Analysis", "Social Innovation", "Community engagement"],
    partner: "Suankularb Wittayalai School และ Nakhonpathom City Municipality",
  },
  {
    category: "camp",
    image: "/work/09.jpg",
    sortDate: "2026-06-27",
    title: "Rise Up: Transforming Leaders into Next-Gen Trainers",
    date: "27-29 มิ.ย. 2569",
    duration: "3 วัน",
    participants: "50 คน",
    topics: ["Advocacy Design", "Knowledge Management", "Learning Design", "Demo Class"],
    partner: "Rights Beyond Border",
  },
  // Workshops
  {
    category: "workshop",
    image: "/work/10.jpg",
    sortDate: "2023-02-01",
    title: "Thai Youth's Civic Imagination and Social Innovation Project",
    date: "ก.พ. 2566 - ม.ค. 2567",
    duration: "11 เดือน",
    participants: "20 คน",
    topics: ["Civic imagination", "Social Innovation by Design Thinking", "Creative Communication"],
    partner: "LSEd TU และ the101.pub",
  },
  {
    category: "workshop",
    image: "/work/11.jpg",
    sortDate: "2024-02-01",
    title: "Workshop \"ห้องเรียนไร้กรอบขอบชีส\"",
    date: "ก.พ. - เม.ย. 2567",
    duration: "3 เดือน",
    participants: "120 คน",
    topics: ["Social Normalization", "Human rights", "Self-awareness", "Violence"],
    partner: "TK Park",
  },
  {
    category: "workshop",
    image: "/work/12.jpg",
    sortDate: "2024-03-05",
    title: "Problem-based Learning Camp",
    date: "5 มี.ค. 2567",
    duration: "4 ชั่วโมง",
    participants: "70 คน",
    topics: ["Problem-based Learning", "Problem Solving", "Science Literacy"],
    partner: "Satthasamut School",
  },
  {
    category: "workshop",
    image: "/work/13.jpg",
    sortDate: "2024-03-16",
    title: "CBA Middle Manager Workshop",
    date: "16 มี.ค. 2567",
    duration: "3 ชั่วโมง",
    participants: "60 คน",
    topics: ["Understand how business run", "Adaptability Quotient", "Team building"],
    partner: "Chulalongkorn Business Administration (CBA)",
  },
  {
    category: "workshop",
    image: "/work/14.jpg",
    sortDate: "2024-04-01",
    title: "Dream Expo, Wooden Bridge and Catapult Workshop",
    date: "1-3 เม.ย. 2567",
    duration: "3 วัน",
    participants: "300 คน",
    topics: ["Weight Distribution", "Structural Integrity", "Energy Transformation", "Projectile"],
    partner: "Assumption College",
  },
  {
    category: "workshop",
    image: "/work/15.jpg",
    sortDate: "2024-05-18",
    title: "Puppet Theatre Workshop",
    date: "18 พ.ค. 2567",
    duration: "4 ชั่วโมง",
    participants: "20 คน",
    topics: ["Puppet making", "Applied theatre", "Environmental-awareness"],
    partner: "Pathumyouth, Influencer th และ สสส.",
  },
  {
    category: "workshop",
    image: "/work/16.jpg",
    sortDate: "2024-05-25",
    title: "Environmental-awareness for Teacher",
    date: "25-26 พ.ค. 2567",
    duration: "2 วัน",
    participants: "300 คน",
    topics: ["Garbage recycling", "Environmental-awareness", "Creative Drama"],
    partner: "World Wildlife Fund, Ranong Recycle for Environment และ Surat Thani City Municipality",
  },
  {
    category: "workshop",
    image: "/work/17.jpg",
    sortDate: "2024-06-20",
    title: "Herbal Inhalant Making Workshop",
    date: "20 มิ.ย. 2567",
    duration: "4 ชั่วโมง",
    participants: "100 คน",
    topics: ["Thai culture", "Properties of herbs", "Inhalant making"],
    partner: "Amnuay Silpa School",
  },
  {
    category: "workshop",
    image: "/work/18.jpg",
    sortDate: "2024-07-12",
    title: "Giftwise's Q2 Townhall 2024",
    date: "12 ก.ค. 2567",
    duration: "3 ชั่วโมง",
    participants: "70 คน",
    topics: ["Active Listening", "Effective Feedback", "Non-violence Communication"],
    partner: "Giftwise Asia",
  },
  {
    category: "workshop",
    image: "/work/19.jpg",
    sortDate: "2024-08-04",
    title: "Workshop \"คนตัวเล็ก ขอเล่นใหญ่\" @Learning Fest 2024",
    date: "4 ส.ค. 2567",
    duration: "1 วัน",
    participants: "25 คน",
    topics: ["Civic Imagination", "Social Problem Analysis", "Self-Awareness", "Social Innovation"],
    partner: "TK Park",
  },
  {
    category: "workshop",
    image: "/work/20.jpg",
    sortDate: "2024-09-13",
    title: "Workshop \"การทำสื่อสร้างสรรค์และละครเพื่อการเรียนรู้\"",
    date: "13 ก.ย. 2567",
    duration: "1 วัน",
    participants: "110 คน",
    topics: ["Creative Drama", "Team building"],
    partner: "วิทยากรทีมงานบ้านอรชุน และ โรงเรียนเทศบาลวัดป่าแพ่ง",
  },
  {
    category: "workshop",
    image: "/work/21.jpg",
    sortDate: "2024-11-27",
    title: "AC Engineer Camp 2024",
    date: "27 พ.ย. 2567",
    duration: "1 วัน",
    participants: "100 คน",
    topics: ["Basic Engineering", "STEM Education", "Projectile", "Product Design"],
    partner: "Assumption College",
  },
  {
    category: "workshop",
    image: "/work/22.jpg",
    sortDate: "2025-01-17",
    title: "Giftwise's Q1 Townhall 2025",
    date: "17 ม.ค. 2568",
    duration: "1 วัน",
    participants: "90 คน",
    topics: ["DISC for collaboration", "Team building", "Problem solving"],
    partner: "Giftwise Asia",
  },
  {
    category: "workshop",
    image: "/work/23.jpg",
    sortDate: "2025-02-01",
    title: "House of Wisdom TU Workshop 2025",
    date: "ก.พ. - เม.ย. 2568",
    duration: "3 เดือน / 8 sessions",
    participants: "300+ คน",
    topics: ["Performance arts", "Crafting", "Art", "Reflection"],
    partner: "House of Wisdom TU",
  },
  {
    category: "workshop",
    image: "/work/24.jpg",
    sortDate: "2025-03-27",
    title: "AC Engineering Design Process Workshop",
    date: "27 มี.ค. 2568",
    duration: "1 วัน",
    participants: "60 คน",
    topics: ["Basic Engineering", "STEM Education", "Design Process", "Truss Structure"],
    partner: "Assumption College",
  },
  {
    category: "workshop",
    image: "/work/25.jpg",
    sortDate: "2025-04-01",
    title: "VetMed KU Student Committee Orientation",
    date: "1 เม.ย. 2568",
    duration: "1 วัน",
    participants: "75 คน",
    topics: ["Non-violent communication", "Constructive Feedback", "Empathetic listening"],
    partner: "VetMed KU",
  },
  {
    category: "workshop",
    image: "/work/26.jpg",
    sortDate: "2025-05-02",
    title: "TSS Student Orientation Camp",
    date: "2-3 พ.ค. 2568",
    duration: "2 วัน",
    participants: "100 คน",
    topics: ["Team building", "Creativity", "Self-Awareness"],
    partner: "Thammasat Secondary School",
  },
  {
    category: "workshop",
    image: "/work/27.jpg",
    sortDate: "2025-05-20",
    title: "TSS Student Council Orientation",
    date: "20 พ.ค. 2568",
    duration: "1 วัน",
    participants: "25 คน",
    topics: ["DISC for leadership", "Non-violent communication", "Team building"],
    partner: "Thammasat Secondary School",
  },
  {
    category: "workshop",
    image: "/work/28.jpg",
    sortDate: "2025-05-25",
    title: "CBA Middle Manager Training: The Art of Teamwork",
    date: "25 พ.ค. 2568",
    duration: "1 วัน",
    participants: "25 คน",
    topics: ["Effective Communication", "Iceberg model", "GROW model for problem solving"],
    partner: "Chulalongkorn Business Administration (CBA)",
  },
  {
    category: "workshop",
    image: "/work/29.jpg",
    sortDate: "2025-06-21",
    title: "Unlock Your Leadership - SMO Banshix กวศ.",
    date: "21 มิ.ย. 2568",
    duration: "1 วัน",
    participants: "25 คน",
    topics: ["DISC for leadership", "Leadership skills/mindsets", "Team management"],
    partner: "SMO Banshi, ESC CU และ CaMP by ChAMP",
  },
  {
    category: "workshop",
    image: "/work/30.jpg",
    sortDate: "2025-11-13",
    title: "AC Bridgemaster Workshop",
    date: "13 พ.ย. 2568",
    duration: "1 วัน",
    participants: "100 คน",
    topics: ["Basic Engineering", "STEM Education", "Truss Structure"],
    partner: "Assumption College",
  },
  {
    category: "workshop",
    image: "/work/31.jpg",
    sortDate: "2025-12-20",
    title: "BCC Problem Discovery Class",
    date: "20 ธ.ค. 2568",
    duration: "1 วัน",
    participants: "40 คน",
    topics: ["Problem discovery", "Problem in daily life", "Solution Ideation"],
    partner: "Bangkok Christian College",
  },
  {
    category: "workshop",
    image: "/work/32.jpg",
    sortDate: "2026-02-20",
    title: "Awaken Your Purpose: วิชาปั้นฝัน 101",
    date: "20 ก.พ. 2569",
    duration: "1 วัน",
    participants: "50 คน",
    topics: ["Designing Your Life", "SMART Goals", "Finding Strength"],
    partner: "Bangkok Christian College",
  },
  {
    category: "workshop",
    image: "/work/33.jpg",
    sortDate: "2026-03-07",
    title: "AC STEM Workshop: Turbo Motion Challenge",
    date: "7 มี.ค. 2569",
    duration: "1 วัน",
    participants: "300 คน",
    topics: ["Basic Engineering", "STEM Education", "Basic Electrical Circuit", "Product Design"],
    partner: "Assumption College",
  },
  {
    category: "workshop",
    image: "/work/34.jpg",
    sortDate: "2026-03-31",
    title: "AC Escape Room - DREAM Expo 2026: Your Dream is…",
    date: "31 มี.ค. - 3 เม.ย. 2569",
    duration: "4 วัน / 16 sessions",
    participants: "400 คน",
    topics: ["Sciences in Daily Life", "Problem Solving", "Interdisciplinary Task"],
    partner: "Assumption College",
  },
  {
    category: "workshop",
    image: "/work/35.jpg",
    sortDate: "2026-03-31",
    title: "AC STEM Workshop: Wooden Skyscraper",
    date: "31 มี.ค. 2569",
    duration: "1 วัน",
    participants: "100 คน",
    topics: ["Basic Engineering", "STEM Education", "Truss Structure"],
    partner: "Assumption College",
  },
  {
    category: "workshop",
    image: "/work/36.jpg",
    sortDate: "2026-05-13",
    title: "House of The Saint: Teacher Orientation",
    date: "13 พ.ค. 2569",
    duration: "1 วัน",
    participants: "340 คน",
    topics: ["Student Care System", "Team bonding", "Project creation"],
    partner: "Saint Gabriel's College",
  },
  {
    category: "workshop",
    image: "/work/37.jpg",
    sortDate: "2026-06-19",
    title: "TPN English Magic Camp",
    date: "19 มิ.ย. 2569",
    duration: "1 วัน",
    participants: "100 คน",
    topics: ["English communication", "Debating in English", "Self-Confidence"],
    partner: "Triamudomsuksa Pattanakarn Nonthaburi School",
  },
  {
    category: "workshop",
    image: "/work/38.jpg",
    sortDate: "2026-07-09",
    title: "The Numbers Behind the Story",
    date: "9 ก.ค. 2569",
    duration: "1 วัน",
    participants: "26 คน",
    topics: ["Storytelling", "Body Language", "Talk Creation"],
    partner: "Satriwithaya School",
  },
  // Miscellaneous
  {
    category: "misc",
    image: "/work/39.jpg",
    sortDate: "2024-06-05",
    title: "Anti-addictive Substances Stageplay",
    date: "5 มิ.ย. - 19 ก.ค. 2567",
    duration: "24 วัน / 48 sessions",
    participants: "10,000+ คน",
    topics: ["Types of addictive substances", "Consequences of addiction", "Drama"],
    partner: "Samut Prakan Provincial Administrative Organization",
  },
  {
    category: "misc",
    image: "/work/40.jpg",
    sortDate: "2024-10-09",
    title: "เวที \"ร่วมพัฒนาโรงเรียน\" ณ โรงเรียนบ้านบางหมาก",
    date: "9-10 ต.ค. 2567",
    duration: "2 วัน",
    participants: "60 คน",
    topics: ["Creative Communication", "Applied theatre", "Cultural heritages"],
    partner: "LSEd TU, โครงการโรงเรียนร่วมพัฒนา และ Ban Bangmak School",
  },
  {
    category: "misc",
    image: "/work/41.jpg",
    sortDate: "2024-10-31",
    title: "SKE2024 Suankularb Innovation Contest",
    date: "31 ต.ค. 2567",
    duration: "1 วัน",
    participants: "80 คน",
    topics: ["Design Thinking", "Innovation", "Pitching"],
    partner: "Suankularb Wittayalai School",
  },
  {
    category: "misc",
    image: "/work/42.jpg",
    sortDate: "2024-11-09",
    title: "SYSI Curate Your Pitch & Talk Workshop",
    date: "9 พ.ย. 2567",
    duration: "1 วัน",
    participants: "40 คน",
    topics: ["Story-telling for social innovation", "Pitching", "Stage Performance"],
    partner: "SYSI และ Connect Fest 3",
  },
  {
    category: "misc",
    image: "/work/43.jpg",
    sortDate: "2024-12-01",
    title: "Interactive Learning Exhibition \"สายลับนากน้อย\"",
    date: "1 ธ.ค. 2567",
    duration: "1 วัน",
    participants: "200 คน",
    topics: ["Community engagement", "Cultural heritages", "Applied theatre"],
    partner: "LSEd TU และ โครงการโรงเรียนร่วมพัฒนา",
  },
  {
    category: "misc",
    image: "/work/44.jpg",
    sortDate: "2025-02-28",
    title: "Giftwise's Excel Training",
    date: "28 ก.พ. 2568",
    duration: "1 วัน",
    participants: "30 คน",
    topics: ["Excel for corporate"],
    partner: "Giftwise Asia",
  },
  {
    category: "misc",
    image: "/work/45.jpg",
    sortDate: "2025-07-07",
    title: "เส้นทางฝันกับพอร์ตในมือ - TCAS Portfolio Guidance",
    date: "7 ก.ค. 2568",
    duration: "1 วัน",
    participants: "300 คน",
    topics: ["Portfolio guidance", "Storytelling for Portfolio", "TCAS preparation"],
    partner: "Khemasiri Memorial School",
  },
  {
    category: "misc",
    image: "/work/46.jpg",
    sortDate: "2025-07-29",
    title: "YES Talent Camp 2025 - GenAI Hackathon - Orientation Day",
    date: "29 ก.ค. 2568",
    duration: "1 วัน",
    participants: "120 คน",
    topics: ["Teambuilding", "Potential Seeking", "Pitching Simulation"],
    partner: "Mitr Phol Group",
  },
  {
    category: "misc",
    image: "/work/47.jpg",
    sortDate: "2026-03-12",
    title: "ถอดบทเรียนสะท้อนคิด โครงการ \"Craft AI\"",
    date: "12 มี.ค. 2569",
    duration: "1 วัน",
    participants: "30 คน",
    topics: ["Reflection", "Learning Milestones", "Finding Next-step"],
    partner: "LSEd TU และ บพท.",
  },
];

export const portfolio = [...portfolioRaw].sort((a, b) =>
  b.sortDate.localeCompare(a.sortDate)
);
